-- ============================================================
--  HBSHUD  –  Server
--  Minimal server side — all stats are read client-side
--  via exports.qbx_core:GetPlayerData().
-- ============================================================
